#!/usr/bin/env bash
#
# Generate Terraform docs for the ABP resources/data sources only and place
# them into the legacy `website/` layout used by the rest of this provider.
#
# tfplugindocs has no per-resource filter: it always renders the whole
# provider schema. So we generate everything into a throwaway dir, then copy
# out only the files whose name contains `abp_`, converting them to the legacy
# layout (`.html.markdown` extension + `incapsula` front matter).
#
# Prerequisite:
#   go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest
#
# Usage:
#   scripts/gen-abp-docs.sh          # skip resources that already have a hand-written doc
#   FORCE=1 scripts/gen-abp-docs.sh  # overwrite even when a legacy doc already exists

set -euo pipefail

PROVIDER_NAME="incapsula"
SUBCATEGORY="Advanced Bot Protection"

# Repo root = parent of this script's dir.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v tfplugindocs >/dev/null 2>&1; then
  echo "ERROR: tfplugindocs not found in PATH." >&2
  echo "Install it with:" >&2
  echo "  go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest" >&2
  echo "and make sure \$(go env GOPATH)/bin is in your PATH." >&2
  exit 1
fi

GEN_DIR=".tmp/abp-docs"   # .tmp/ is gitignored
rm -rf "$GEN_DIR"
mkdir -p "$GEN_DIR"

echo "==> Generating full provider docs into $GEN_DIR (only abp_* will be kept)..."
tfplugindocs generate \
  --provider-name "$PROVIDER_NAME" \
  --rendered-website-dir "$GEN_DIR"

# Transform a single generated file into the legacy layout and write it to $2.
# Rewrites the front matter to match website/docs/r/abp_websites.markdown:
#   - drop the tfplugindocs generator comment
#   - force subcategory to "Advanced Bot Protection"
#   - add layout: "incapsula"
#   - shorten page_title to just the resource name (strip " Resource|Data Source - incapsula")
#   - keep the description block as-is, blank line after the closing ---
# Also strips the " (Resource)"/" (Data Source)" suffix from the H1 heading.
transform() {
  local src="$1" dst="$2"
  awk -v subcat="$SUBCATEGORY" '
    BEGIN { fm = 0; dn = 0 }
    NR == 1 && $0 == "---" { fm = 1; print "---"; next }
    fm == 1 && $0 == "---" {
      print "subcategory: \"" subcat "\""
      print "layout: \"incapsula\""
      print "page_title: \"" pt "\""
      for (i = 0; i < dn; i++) print desc[i]
      print "---"
      print ""        # blank line after front matter (legacy convention)
      fm = 2
      next
    }
    fm == 1 {
      if ($0 ~ /^# generated by/) next
      if ($0 ~ /^page_title:/) {
        if (match($0, /"[^"]*"/)) {
          q = substr($0, RSTART + 1, RLENGTH - 2)
          split(q, parts, " ")
          pt = parts[1]
        }
        next
      }
      if ($0 ~ /^subcategory:/) next   # overridden above
      desc[dn++] = $0                  # description: |- and its indented lines
      next
    }
    fm == 2 {
      sub(/ \(Resource\)$/, "")
      sub(/ \(Data Source\)$/, "")
      print
      next
    }
    { print }
  ' "$src" > "$dst"
}

# Copy abp_* files from one generated subdir into a legacy target dir.
#   $1 = generated subdir (resources | data-sources)
#   $2 = legacy target dir (website/docs/r | website/docs/d)
copy_kind() {
  local gen_sub="$1" target_dir="$2"
  local src base stem existing
  shopt -s nullglob
  for src in "$GEN_DIR/$gen_sub"/*abp_*.md; do
    base="$(basename "${src%.md}")"          # e.g. abp_site

    # `incapsula_abp_websites` has a hand-written doc; never regenerate it.
    if [ "$base" = "abp_websites" ]; then
      echo "  IGNORE $base — excluded from generation"
      continue
    fi

    stem="$target_dir/$base"

    # Collision check: any pre-existing legacy doc for this resource,
    # regardless of extension (.markdown or .html.markdown).
    existing=""
    for cand in "$stem.html.markdown" "$stem.markdown"; do
      [ -f "$cand" ] && existing="$cand"
    done
    if [ -n "$existing" ] && [ "${FORCE:-0}" != "1" ]; then
      echo "  SKIP $base — legacy doc already exists: $existing (set FORCE=1 to overwrite)"
      continue
    fi

    transform "$src" "$stem.html.markdown"
    echo "  wrote $stem.html.markdown"
  done
  shopt -u nullglob
}

echo "==> Placing ABP resource docs into website/docs/r ..."
copy_kind "resources" "website/docs/r"

echo "==> Placing ABP data-source docs into website/docs/d ..."
copy_kind "data-sources" "website/docs/d"

echo "==> Cleaning up $GEN_DIR ..."
rm -rf "$GEN_DIR"

echo "Done. Review the new website/docs/{r,d}/abp_*.html.markdown files,"
echo "and add sidebar entries in website/incapsula.erb if needed."
