name: Build Provider
on:
  push:
    tags: 
      - 'v*' # Push events to matching v*, i.e. v1.0, v2.1.0, v10.1.1-alpha

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      REPO_NAME: terraform-provider-incapsula
    steps:
    - name: Install Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: Setup env
      run: |
        export GOPATH=$HOME/go
        echo "GOPATH=$GOPATH" >> $GITHUB_ENV
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/terraform-providers/$REPO_NAME
        mv $(pwd)/* $GOPATH/src/github.com/terraform-providers/$REPO_NAME
    - name: Test
      run: |
        cd $GOPATH/src/github.com/terraform-providers/$REPO_NAME
        make test
    - name: Build
      id: build
      run: |
        cd $GOPATH/src/github.com/terraform-providers/$REPO_NAME
        make build
        ls -l $GOPATH/bin
        echo ::set-output name=ARTIFACT_PATH::$GOPATH/bin
        echo ::set-output name=ARTIFACT_NAME::terraform-provider-incapsula
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ${{ steps.build.outputs.ARTIFACT_PATH }}/${{ steps.build.outputs.ARTIFACT_NAME }}
        asset_name: ${{ steps.build.outputs.ARTIFACT_NAME }}
        asset_content_type: application/octet-stream
